spring.application.name=auth-service
server.port=8080

spring.threads.virtual.enabled=true

# Keycloak issuer URL (adjust realm name once created)
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI}

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://tempo.observability.svc.cluster.local:4318/v1/traces
