apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-kafka
  namespace: argocd
spec:
  project: default
  source:
    repoURL: quay.io/strimzi-helm
    chart: strimzi-kafka-operator
    targetRevision: 0.44.0
  destination:
    server: https://kubernetes.default.svc
    namespace: data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka
  namespace: data
spec:
  kafka:
    version: 3.9.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
