apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-clickhouse
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: clickhouse
    targetRevision: 10.4.28
    helm:
      values: |
        replicaCount: 1
        auth:
          username: default
          password: clickhouse
        persistence:
          enabled: true
          size: 2Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: analytics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
