apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-keycloak
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: keycloak
    targetRevision: 25.2.0
    helm:
      values: |
        auth:
          adminUser: admin
          adminPassword: admin
        postgresql:
          enabled: true
          auth:
            username: keycloak
            password: keycloak-password
            database: keycloak
        proxy: edge
        service:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: identity
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
