apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-spring-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/victorrumanski/my-spring-service.git'
    targetRevision: HEAD
    path: charts/my-spring-service
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
