apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/victorrumanski/senior-e-commerce.git
    targetRevision: HEAD
    path: argocd-apps
    directory:
      recurse: true
      include: 'observability-*.yaml'
      exclude: 'observability-app-of-apps.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
