apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 83.6.0
    helm:
      values: |
        grafana:
          enabled: true
          adminPassword: admin
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - grafana.localtest.me
          additionalDataSources:
            - name: Loki
              type: loki
              access: proxy
              url: http://loki.observability.svc.cluster.local:3100
              isDefault: false
            - name: Tempo
              type: tempo
              access: proxy
              url: http://tempo.observability.svc.cluster.local:3100
              isDefault: false
        prometheus:
          ingress:
            enabled: false
        alertmanager:
          ingress:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
