apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.53.0
    helm:
      values: |
        loki:
          auth_enabled: false
        singleBinary:
          replicas: 1
        read:
          replicas: 0
        write:
          replicas: 0
        backend:
          replicas: 0
        gateway:
          enabled: false
        service:
          port: 3100
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
