name: Catalog Service CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "services/catalog-service/**"
      - ".github/workflows/reusable-service-build.yml"
      - ".github/workflows/catalog-service-build.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "services/catalog-service/**"

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/reusable-service-build.yml
    with:
      service_path: services/catalog-service
      service_name: catalog-service
