name: Inventory Service CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "services/inventory-service/**"
      - ".github/workflows/reusable-service-build.yml"
      - ".github/workflows/inventory-service-build.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "services/inventory-service/**"

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/reusable-service-build.yml
    with:
      service_path: services/inventory-service
      service_name: inventory-service
