name: Notifications Service CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "services/notifications-service/**"
      - ".github/workflows/reusable-service-build.yml"
      - ".github/workflows/notifications-service-build.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "services/notifications-service/**"

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/reusable-service-build.yml
    with:
      service_path: services/notifications-service
      service_name: notifications-service
